### ISSUE TITLE
I get an error when preparing boot files

### ISSUE THREAD

**Issue by maxiwee69** [mineek/seprmvr64#1]
when I img4 -i trustcache -o trustcache.img4 -M IM4M -T rtsc
I get [e] cannot open 'trustcache'

**Comment by iarchiveml** [comment]
Don't try to use something you are clueless about.

**Comment by maxiwee69** [comment]
How about actually answering and not just saying bs

**Comment by maxiwee69** [comment]
btw i fixed it myself and I noticed my brain fart
